#!/usr/bin/env bash

playground()
{
	local dir="/tmp/Playground"
	[[ -d $dir ]] || mkdir $dir
	cd $dir && clear
}

json()
{
	python -mjson.tool
}

server()
{
	local port=${1:-8000}
	echo "Serving HTTP on 0.0.0.0 port $port"
	python -mSimpleHTTPServer "$port" &> /dev/null
	echo
}

pd()
{
	local dir="$1"
	if [[ "$dir" == "-" ]]
	then
		popd &> /dev/null
	elif [[ -d "$dir" ]]
	then
		pushd "$dir" &> /dev/null
	else
		return 1
	fi
}

headers() {
	local url="$1"
	curl -s -D - "$url" -o /dev/null
}
