#!/usr/bin/env bash

playground()
{
	local dir="/tmp/Playground"
	[[ -d $dir ]] || mkdir $dir
	cd $dir && clear
}

json()
{
	python -mjson.tool
}

server()
{
	local port=${1:-8000}
	echo "Serving HTTP on 0.0.0.0 port $port"
	python -mSimpleHTTPServer "$port" &> "$ABYSS"
	echo
}

pd()
{
	local dir="$1"
	if [[ "$dir" == "-" ]]
	then
		popd &> "$ABYSS"
	elif [[ -d "$dir" ]]
	then
		pushd "$dir" &> "$ABYSS"
	else
		return 1
	fi
}
