#!/usr/bin/env bash

la()
{
	ls -Alv "$@"
}

lad()
{
	la "$@" | grep --color=auto --extended-regexp "^d" # Only show directories
}

lal()
{
	la "$@" | grep --color=auto --extended-regexp "^l" # Only show symlinks
}

laf()
{
	la "$@" | grep --color=auto --extended-regexp --invert-match "(^d)|(^l)" # Only show files
}
