#!/usr/bin/env bash

##########
##########
##      ##
## Java ##
##      ##
##########
##########

alias java32='java -d32' # Run Java in a 32-bit environment if available
alias javac='javac -g:lines,source,vars -Xlint:all'
