#!/usr/bin/env node

!function () {
	var
	url = "https://github.com/whymarrh?tab=repositories",
	api = "https://status.github.com/api/last-message.json",
	https = require("https"),
	util  = require("util"),
	openGitHub = function () {
		require("child_process").exec("open " + url);
	},
	githubStatus = function () {
		https.get(api, function(response) {
			var obj = "";
			response.on("data", function (chunk) {
				obj += chunk;
			});
			response.on("end", function () {
				var lmsg = JSON.parse(obj);
				util.puts(lmsg.body);
			})
		}).on("error", function(e) {
			util.puts("Whoa. Something went wrong.");
		});
	};
	switch (process.argv[2]) {
		case "status":
			githubStatus();
			break;
		case "open":
			openGitHub();
			break;
	}
}();
