#!/usr/bin/env bash

############
############
##        ##
## Editor ##
##        ##
############
############

export EDITOR="vim"

#############
#############
##         ##
## History ##
##         ##
#############
#############

export FIGNORE="Application Scripts"
export HISTCONTROL=ignoreboth
export HISTFILE=/dev/null
export HISTSIZE=
export HISTTIMEFORMAT="%Y-%m-%dT%H:%M:%S%z  "

##########
##########
##      ##
## PATH ##
##      ##
##########
##########

__www_create_path ()
{
	PATH=
	local directories=(
		"/opt/yarn/bin"
		"/usr/local/bin"
		"/usr/bin"
		"/bin"
		"/usr/sbin"
		"/sbin"
		"/usr/local/go/bin"
		"$HOME/.cargo/bin"
		"$HOME/.files/bin"
	)
	for i in "${directories[@]}"
	do
		[[ -d "$i" ]] && PATH=$PATH:"$i"
	done
	PATH=${PATH:1}
}

__www_create_path
unset -f __www_create_path

##############
##############
##          ##
##  Prompt  ##
##          ##
##############
##############

__www_set_prompt ()
{
	local reset_colour='\[\033[0m\]'
	local cyan='\[\033[0;36m\]'
	local gray='\[\033[0;37m\]'
	local git_prompt='$(__git_ps1 "(%s) ")'
	local white_bold='\[\033[1;37m\]'
	local virtualenv='$(test -z "$VIRTUAL_ENV" || printf "(virtualenv: %s) " $(basename "$VIRTUAL_ENV"))'
	local jobcount='$([ \j -gt 0 ] && printf "(%dj) " \j)'

	if [[ $(uname) == "Darwin" ]]
	then
		PS1="\t ${gray}${virtualenv}${cyan}\W ${jobcount}${git_prompt}$ ${reset_colour}"
	fi
	if [[ $(uname) == "Linux" ]]
	then
		PS1="${white_bold}\h${reset_colour} | \W $ "
	fi
}

__www_set_prompt
unset -f __www_set_prompt
