#!/usr/bin/env bash

#########
#########
##     ##
## SSH ##
##     ##
#########
#########

if [[ -f "$HOME/.ssh/config" ]]
then
	complete -o "default" -W \
	"$(grep "^Host" "$HOME/.ssh/config" | grep -v "[?*]" | cut -d " " -f2)" \
	scp sftp ssh
fi
