#!/usr/bin/env bash

[[ $(uname) != "Darwin" ]] && return

defaults write NSGlobalDomain LSAppNapIsDisabled -bool YES
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true
defaults write com.apple.screencapture location -string "$HOME/Downloads"
